"""empty message

Revision ID: 05603c9b942e
Revises: ff66ddce50ce
Create Date: 2020-09-24 22:58:23.324909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05603c9b942e'
down_revision = 'ff66ddce50ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('resolve_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bugs_report_date'), 'bugs', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bugs_report_date'), table_name='bugs')
    op.drop_column('bugs', 'resolve_date')
    # ### end Alembic commands ###
