"""empty message

Revision ID: 601c35451e20
Revises: 0c5817f69207
Create Date: 2020-10-06 18:10:10.724257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601c35451e20'
down_revision = '0c5817f69207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_settings', sa.Column('menu_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_settings', 'menu_color')
    # ### end Alembic commands ###
