"""empty message

Revision ID: 9e254c7fba53
Revises: 
Create Date: 2020-09-29 19:42:26.738164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e254c7fba53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=22), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('access_code', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_creation_date'), 'projects', ['creation_date'], unique=False)
    op.create_index(op.f('ix_projects_expiry_date'), 'projects', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_projects_url'), 'projects', ['url'], unique=True)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permalink', sa.String(length=22), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_author'), 'blog_posts', ['author'], unique=False)
    op.create_index(op.f('ix_blog_posts_permalink'), 'blog_posts', ['permalink'], unique=True)
    op.create_index(op.f('ix_blog_posts_project'), 'blog_posts', ['project'], unique=False)
    op.create_table('project_bug_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_bug_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('bug_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_url', sa.String(length=100), nullable=True),
    sa.Column('current_version', sa.String(length=20), nullable=True),
    sa.Column('header_color', sa.String(length=7), nullable=True),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('link_color', sa.String(length=7), nullable=True),
    sa.Column('per_page', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('allow_suggestions', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_settings_current_version'), 'project_settings', ['current_version'], unique=False)
    op.create_table('users_to_projects',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proj_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('author_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('resolve_date', sa.DateTime(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('bug_location', sa.Integer(), nullable=True),
    sa.Column('bug_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bug_location'], ['project_bug_locations.id'], ),
    sa.ForeignKeyConstraint(['bug_type'], ['project_bug_types.id'], ),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bugs_ref_id'), 'bugs', ['ref_id'], unique=True)
    op.create_index(op.f('ix_bugs_report_date'), 'bugs', ['report_date'], unique=False)
    op.create_index(op.f('ix_bugs_version'), 'bugs', ['version'], unique=False)
    op.create_table('bug_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('bug', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bug'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug_comments')
    op.drop_index(op.f('ix_bugs_version'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_report_date'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_ref_id'), table_name='bugs')
    op.drop_table('bugs')
    op.drop_table('users_to_projects')
    op.drop_index(op.f('ix_project_settings_current_version'), table_name='project_settings')
    op.drop_table('project_settings')
    op.drop_table('project_bug_types')
    op.drop_table('project_bug_locations')
    op.drop_index(op.f('ix_blog_posts_project'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_permalink'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_author'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_projects_url'), table_name='projects')
    op.drop_index(op.f('ix_projects_expiry_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_creation_date'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
