"""empty message

Revision ID: b40adac021c1
Revises: 221419fcc8c7
Create Date: 2020-09-22 21:37:12.252363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40adac021c1'
down_revision = '221419fcc8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('report_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bugs_report_date'), 'bugs', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bugs_report_date'), table_name='bugs')
    op.drop_column('bugs', 'report_date')
    # ### end Alembic commands ###
