"""empty message

Revision ID: ff66ddce50ce
Revises: bde5dcecb157
Create Date: 2020-09-24 22:57:18.209865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff66ddce50ce'
down_revision = 'bde5dcecb157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bugs_report_date', table_name='bugs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bugs_report_date', 'bugs', ['report_date'], unique=False)
    # ### end Alembic commands ###
